// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUGsWK6MQFlKKrWc7KJzcmnA2wmgcrOb4',
    appId: '1:548133283838:web:fba492f06278e6f8d442af',
    messagingSenderId: '548133283838',
    projectId: 'chat-bot-93773',
    authDomain: 'chat-bot-93773.firebaseapp.com',
    storageBucket: 'chat-bot-93773.appspot.com',
    measurementId: 'G-H4HTYSPT3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4_ixFqc_12fLPQ3w3oERqBS9fgnMeUNA',
    appId: '1:548133283838:android:34ec143cdf923043d442af',
    messagingSenderId: '548133283838',
    projectId: 'chat-bot-93773',
    storageBucket: 'chat-bot-93773.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA13UsyW1d0pR70LaI_nH1aILMgufirJlw',
    appId: '1:548133283838:ios:02a7b3caf88a152fd442af',
    messagingSenderId: '548133283838',
    projectId: 'chat-bot-93773',
    storageBucket: 'chat-bot-93773.appspot.com',
    iosBundleId: 'com.example.chatGpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA13UsyW1d0pR70LaI_nH1aILMgufirJlw',
    appId: '1:548133283838:ios:6cc3e785b28924a2d442af',
    messagingSenderId: '548133283838',
    projectId: 'chat-bot-93773',
    storageBucket: 'chat-bot-93773.appspot.com',
    iosBundleId: 'com.example.chatGpt.RunnerTests',
  );
}
